### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by rmbryan71** [bobby-pancakes/docs-basic-portfolio#1]
In the Portfolio Examples section, the link to http://www.kirabutler.com/ returns "Site Not Found".

**Comment by bobby-pancakes** [comment]
Ah, thank you for letting me know! I'll fix that link ASAP.

**Comment by bobby-pancakes** [comment]
I addressed this in commit [32f5c41](https://github.com/bobby-pancakes/docs-basic-portfolio/commit/32f5c41f56ceea9b3d7caf521e2ce78e90515dd2).

Looks like that site no longer exists. I replaced it with a couple of other interesting portfolio sites.
